"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { FileText, ListFilter, MessagesSquare } from "lucide-react";
import { useRouter } from "next/navigation";
import Button from "../../components/ui/button";
import Card from "../../components/ui/card";
import { api } from "../../lib/api-client";
import { templates, templateFor, type Definition, type OwnedAgent } from "../../lib/owned-agent/templates";
import "./preview.css";
export default function SummaryPreview({ enabled, hosted = false, canSave = false, request = api }: { enabled: boolean; hosted?: boolean; canSave?: boolean; request?: typeof api }) {
  const router=useRouter();
  const openedLink=useRef<string|null>(null);
  const [template,setTemplate]=useState<Definition['template']>('summary');
  const [name,setName]=useState(''); const [instructions,setInstructions]=useState('');
  const [fields,setFields]=useState('invoice number, vendor, amount, due date'); const [reference,setReference]=useState('');
  const [saved,setSaved]=useState<OwnedAgent[]>([]); const [selected,setSelected]=useState<OwnedAgent>();
  const [text,setText]=useState(''); const [result,setResult]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const [history,setHistory]=useState<Array<{id:string;status:string;output:string|null;created_at:string}>>([]);
  useEffect(()=>{ let active=true;if(canSave) request<OwnedAgent[]>('owned').then(value=>{if(active)setSaved(value);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[canSave,request]);
  useEffect(()=>{let active=true;setHistory([]);if(hosted&&selected) request<typeof history>(`owned/${selected.id}/tests`).then(value=>{if(active)setHistory(value);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[hosted,selected,request,result]);
  useEffect(()=>{const id=new URLSearchParams(location.search).get('agent');const agent=saved.find(a=>a.id===id);if(hosted&&agent&&openedLink.current!==id){openedLink.current=id;setSelected(agent);setTemplate(agent.template);setName(agent.name);setInstructions(agent.instructions);setFields(agent.fields.join(', '));setReference(agent.reference);setText(templateFor(agent.template).example);}},[saved,hosted]);
  function clearSelection(){setSelected(undefined);setResult('');setError('');}
  async function create(){setBusy(true);setError('');try{const agent=await request<OwnedAgent>('owned',{name,template,instructions,fields:template==='extract'?fields.split(',').map(f=>f.trim()).filter(Boolean):[],reference:template==='qa'?reference:''});setSelected(agent);setSaved(await request<OwnedAgent[]>('owned'));if(hosted){window.dispatchEvent(new CustomEvent('hosted-agent-created',{detail:{id:agent.id,name:agent.name,kind:'agent',skills:[templateFor(agent.template).name]}}));window.dispatchEvent(new Event('hosted-workspace-changed'));}setText(templateFor(template).example);setResult('');}catch(e){setError(e instanceof Error?e.message:'Unable to save agent');}finally{setBusy(false);}}
  async function test(){if(!selected)return;setBusy(true);setError('');setResult('');try{const value=await request<{output:string}>(`owned/${encodeURIComponent(selected.id)}/test`,{text});setResult(value.output);}catch(e){setError(e instanceof Error?e.message:'Unable to run agent');}finally{setBusy(false);}}
  function useInWorkflow(agent:OwnedAgent){if(hosted){sessionStorage.setItem('hosted-workflow-step',JSON.stringify({agentId:`template:${agent.id}`,skill:templateFor(agent.template).skill}));router.push('/create');return;}sessionStorage.setItem('general-workflow-step',JSON.stringify({agentId:agent.id,skill:templateFor(agent.template).skill,inputFrom:'original',format:'text',instruction:''}));router.push('/general');}
  return <main className="brief-preview"><div className="brief-eyebrow">BUILD YOUR AGENT <span>THREE STARTING POINTS</span></div><div className="brief-hero"><div><h1>Your purpose.<br/><em>Your agent.</em></h1><p>Choose a template, give it a name, and make it your own. Test it here, then connect it to a workflow.</p></div></div>
    {!canSave&&<p className="brief-notice">Explore the templates below. Use the sign-in link to save and test your agents.</p>}
    <div className="template-grid">{templates.map(t=><button key={t.id} className={`template-option ${template===t.id?'selected':''}`} aria-pressed={template===t.id} disabled={busy} onClick={()=>{setTemplate(t.id);clearSelection();}}><span className="template-symbol" aria-hidden="true">{t.id === "summary" ? <FileText size={22}/> : t.id === "extract" ? <ListFilter size={22}/> : <MessagesSquare size={22}/>}</span><strong>{t.name}</strong><span>{t.description}</span></button>)}</div>
    <div className="brief-workspace"><Card><h2>01 / Configure</h2><label>Agent name<input value={name} maxLength={64} placeholder="e.g. Weekly meeting brief" disabled={busy} onChange={e=>{setName(e.target.value);clearSelection();}}/></label><label>Instructions <span>(optional)</span><textarea value={instructions} maxLength={2000} placeholder="e.g. Keep the brief short and focus on decisions." disabled={busy} onChange={e=>{setInstructions(e.target.value);clearSelection();}}/></label>{template==='extract'&&<label>Fields to extract, separated by commas<input value={fields} disabled={busy} onChange={e=>{setFields(e.target.value);clearSelection();}}/></label>}{template==='qa'&&<label>Reference text<textarea value={reference} maxLength={12000} disabled={busy} placeholder="Paste the document this agent should use to answer questions." onChange={e=>{setReference(e.target.value);clearSelection();}}/></label>}<p className="brief-caption">Saved agents are immutable snapshots. Changing a configuration creates a new agent, so saved definitions keep their behavior.</p><Button block variant="primary" disabled={!canSave||busy||!name.trim()||(template==='qa'&&!reference.trim())} onClick={create}>{busy?'Working…':'Create agent'}</Button></Card>
    <Card><h2>02 / Test your agent</h2>{selected?<><p><strong>{selected.name}</strong> · {templateFor(selected.template).name}</p><label>{selected.template==='qa'?'Question':'Source text'}<textarea value={text} maxLength={12000} disabled={busy} onChange={e=>{setText(e.target.value);setResult('');}}/></label><p className="brief-caption">Testing sends this text, instructions, and any reference document to OpenAI. {hosted && "Inputs and results are saved to your account. Limit: 20 test attempts per UTC day."}</p><Button variant="primary" disabled={busy||!enabled||!text.trim()} onClick={test}>{busy?'Running…':'Test agent'}</Button>{!enabled&&<p className="brief-notice">Testing is not enabled on this server yet.</p>} {<Button disabled={busy} onClick={()=>useInWorkflow(selected)}>Use in workflow →</Button>}</>:<div className="brief-empty"><span>✦</span><h3>Create something useful</h3><p>Save your agent to try it with real input and add it to a workflow.</p></div>}<div aria-live="polite">{error&&<p role="alert" className="brief-notice">{error}</p>}{result&&<div className="brief-result">{result}</div>}</div></Card></div>
    <Card className="saved-created"><h2>Your created agents</h2>{!saved.length?<p className="brief-caption">{canSave ? "No agents saved yet." : "Sign in to view your saved agents."}</p>:saved.map(agent=><div className="created-row" key={agent.id}><div><strong>{agent.name}</strong><p>{templateFor(agent.template).name} · {hosted ? "Hosted account" : "Local"} · Not ANS registered</p></div><Button disabled={busy} onClick={()=>{setSelected(agent);setTemplate(agent.template);setName(agent.name);setInstructions(agent.instructions);setFields(agent.fields.join(', '));setReference(agent.reference);setText(templateFor(agent.template).example);setResult('');setError('');}}>Open</Button>{<Button disabled={busy} onClick={()=>useInWorkflow(agent)}>Use in workflow</Button>}</div>)}</Card>
    {hosted && selected && <Card><h2>Recent tests for {selected.name}</h2>{!history.length && <p>No saved tests yet.</p>}{history.map(run=><article key={run.id}><p>{new Date(run.created_at).toLocaleString()} · {run.status === 'running' ? 'Pending or interrupted — refresh to check the result before retrying' : run.status}</p>{run.output && <pre style={{whiteSpace:'pre-wrap'}}>{run.output}</pre>}</article>)}<p>Use this agent in a hosted workflow. Publishing an A2A endpoint and ANS registration remain separate steps.</p></Card>}
    <footer className="brief-footer"><span>Supplied content only · Review important details · ANS registration pending</span><Link href="/general">Open workflow builder ↗</Link></footer></main>;
}
